title: memories, dreams, reflections
author:
  name: maya tideway
  email: hello@mayatideway.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mayatideway.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 5

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - bin/
  - Gemfile
  - Gemfile.lock
  - lib/
  - Makefile
  - NOTES.org
  - test/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
